services:
  - type: worker
    name: YOUTUBE-BOT
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python HB.py
    repo: https://github.com/sholoomail/YOUTUBE-BOT.git
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
